51 non standard rpc error response from hive rpc node (#52)
* Remove deprecated use of random.sample on sets

* Dealing with bad error response from Hive RPC

Adding some logic to stop this response from Hive bringing down the hivewriter.

```
  File "/home/podping/app/.venv/lib/pypy3.8/site-packages/lighthive/client.py", line 167, in validate_response
    raw_body=response,
lighthive.exceptions.RPCNodeException: Internal Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/podping/app/src/podping_hivewriter/podping_hivewriter.py", line 495, in failure_retry
    ex.raw_body["error"]["data"]["name"]
KeyError: 'name'
```

* Revert "Dealing with bad error response from Hive RPC"

This reverts commit c6d11e193d75d3a45604a2f06ac979ba5fce06ed.

* Fixing issue #51

dealing with a non standard response from a Hive RPC node

* add hotfix to version number

Signed-off-by: Brian of London <brian@podping.org>

* change version to 1.2.5-alpha.0

Signed-off-by: Brian of London <brian@podping.org>

* poetry update dependencies

Co-authored-by: Alecks Gates <alecks@podping.org>